const conf = require("../../../src/configs/sunucuayar.json")
const moment = require("moment");
require("moment-duration-format");
moment.locale("tr");

    let iltifatSayi = 0;
    let iltifatlar = [
      "Seninle her an, hayatın bize sunduğu en kıymetli hediye.",
      "Gülüşün, dünyadaki tüm karanlıkları aydınlatabilecek güce sahip.",
      "Sesini duymak, tüm sıkıntılarımı unutturuyor, kalbime huzur doluyor.",
      "Varlığın, hayatımın en güzel melodisi, seninle her şey daha bir anlamlı.",
      "Seni düşlemek, gecelerimi aydınlatan yıldızlar gibi, her zaman ışık saçıyor.",
      "Yanında olmak, zamanın durduğu bir an gibi, her şey mükemmel.",
      "Seninle geçirilen zaman, ömrüme ömür katıyor.",
      "Sen, benim kalbimin en derininde saklı bir hazinesin.",
      "Gözlerine bakmak, sonsuz bir evrene açılan kapılar gibi.",
      "Sen, ruhumun eşsiz bir parçasısın, seninle tamamlanıyorum.",
      "Senin varlığın, tüm dünya üzerindeki en büyük zenginlik.",
      "Seninle birlikte her yer cennet, her an ise bir ömre bedel.",
      "Sen, kalbimin en derin köşesinde, en özel yerdesin.",
      "Sana her baktığımda, dünyanın en şanslı insanı olduğumu hissediyorum.",
      "Seninle birlikteyken, tüm endişelerim yok oluyor, sadece mutluluk kalıyor.",
      "Seninle geçen her dakika, değerli bir mücevher gibi parlıyor hayatımda.",
      "Senin varlığın, karanlık gecelerime ışık, yalnız anlarıma dostluk getiriyor.",
      "Seninle yaşamak, bu dünyadaki en güzel serüven.",
      "Sen, hayatımda karşılaştığım en büyük mucize, en değerli hazine.",
      "Senin gülüşün, gökyüzündeki tüm yıldızlardan daha parlak.",
      "Seni sevmek, ömrüme ömür katıyor, her günü anlamla dolduruyor.",
      "Seninle her anı yaşamak, bu dünyadaki en değerli armağan.",
      "Sen, kalbimin en derin notalarında çalan bir melodisin.",
      "Seninle olmak, dünya üzerindeki en güzel duygu.",
      "Gözlerin, kalbimin en karanlık köşelerini aydınlatan ışık.",
      "Seninle geçirilen her an, ömür boyu saklanacak bir anı gibi değerli.",
      "Sen, hayatımın en güzel rüyası, uyanmak istemediğim.",
      "Senin varlığın, hayatımın en büyük şansı, en değerli armağanı.",
      "Seninle yaşamak, hayatın sunduğu en kıymetli hikaye.",
      "Mucizelerle dolu bir dünya var, ve sen benim için en büyük mucizesin.",
      "Seninle geçirdiğim her an, hayatımın en değerli zamanı.",
      "Gözlerin, benim için dünyanın en huzurlu yerini temsil ediyor.",
      "Senin varlığın, etrafındakilere mutluluk saçıyor.",
      "Gecenin karanlığında parlayan yıldızlar gibisin, ışığınla yolumu aydınlatıyorsun.",
      "Her sabah uyanmamın sebebi, seninle bir gün daha geçirecek olmam.",
      "Seninle her yer cennet gibi geliyor bana.",
      "Seni düşünmek, kalbime huzur dolduruyor.",
      "Düşlerimin içinde bile sen varsın, gerçek dünyamın en güzel parçası.",
      "Yüzündeki huzur, etrafına yayılıyor ve herkesi mutlu ediyor.",
      "Gülüşün, tüm acıları unutturuyor, yüreğime neşe saçıyor.",
      "Seni beklemek, umudun ve sabrın simgesi olmuş durumda benim için.",
      "Senin ışığın, karanlık dünyamı aydınlatıyor.",
      "Gökyüzündeki en parlak yıldız bile, senin yanında sönük kalır.",
      "Sen, doğal güzelliğin en mükemmel örneğisin.",
      "Gözlerindeki derinlik, okyanusları bile kıskandırır.",
      "Kelimer yetmez seni anlatmaya, sen benim için dünyadaki en değerli varlıksın.",
      "Senin güzelliğin, bahar çiçeklerini bile kıskandırır.",
      "Sen benzersiz bir esersin, dünyada eşi benzeri yok.",
      "Kusursuzluğun, tanrıların bile eseri olamaz, sen dünyanın en mükemmel yaratığısın.",
      "Şiirler, senin güzelliğini anlatmaya yetmez, sen yaşayan bir sanat eserisin.",
      "Dünyanın tüm dilleri bir araya gelse, senin güzelliğini tarif etmeye yetmez.",
      "Senin gülüşün, en karanlık günlerimi aydınlatıyor.",
      "Cennetten bir melek düşmüş olmalısın, çünkü dünyadaki hiçbir şey bu kadar güzel olamaz.",
      "Seni anlatmak için kelime aramak, okyanusta inci aramak gibi, zor ve değerli.",
      "Senin varlığın, bana her günü bayram gibi yaşatıyor.",
      "Seninle geçen her dakika, ömürden çalınmış bir hazine gibi kıymetli.",
      "Senin varlığın, bana hayatın güzelliklerini hatırlatıyor.",
      "Sen, benim hayatımdaki en büyük şanssın, seni bulduğum için kendimi çok şanslı hissediyorum.",
      "Seninle birlikteyken, zamanın nasıl geçtiğini anlamıyorum.",
      "Seni sevmek, yaşamak için en güzel sebep.",
      "Senin gülüşün, tüm dünya için bir ışık kaynağı olabilir.",
      "Sen, gökyüzündeki en parlak yıldızdan daha değerlisin benim için.",
      "Seni düşünmek, kalbimi umut ve sevinçle dolduruyor.",
      "Sen, bu dünyadaki en büyük mucize ve en güzel hediyesin.",
      "Gözlerin, içinde kaybolmak istediğim bir deniz gibi derin ve güzel.",
      "Seninle birlikteyken, dünyanın en zengin insanı gibi hissediyorum.",
      "Sen, hayatımın en güzel rüyasısın, uyanmak istemediğim.",
      "Senin varlığın, hayatıma anlam katıyor ve her şeyi daha güzel yapıyor.",
      "Gözlerindeki parıltı, geceyi gündüze çeviren bir ay gibi.",
      "Seni sevmek, kalbime yazılmış en güzel şiir.",
      "Seninle her geçen gün, hayatımdaki en güzel gün oluyor.",
      "Sen, kalbimin en derin köşesinde sakladığım en değerli hazinesin.",
      "Gözlerin, kalbime yolculuk etmek istediğim sonsuz bir evren.",
      "Seninle birlikte, hayatın tüm renklerini daha canlı görüyorum.",
      "Senin gülüşün, dünyadaki tüm karanlıkları aydınlatabilir.",
      "Sen, benim için vazgeçilmez bir mucizesin, hayatımın en büyük armağanısın.",
      "Her anını seninle geçirmek, hayatımın en değerli anları oluyor.",
      "Senin sevgin, kalbimdeki en büyük güç ve ilham kaynağı.",
      "Gözlerindeki ışık, kalbimin en karanlık köşelerini bile aydınlatıyor.",
      "Sen, hayatımın melodisi, gülüşün müziğimin en güzel notası.",
      "Seninle birlikte olmak, dünyanın en büyük mutluluğu.",
      "Her sabah seninle uyanmanın hayaliyle doluyor gözlerim.",
      "Senin sesin, en güzel şarkılardan daha etkileyici, kalbimi dans ettiriyor.",
      "Seninle birlikteyken, dünya daha yaşanılır, her an daha kıymetli.",
      "Sen, hayatımdaki en büyük aşk romanının kahramanısın.",
      "Gülüşün, üzerime düşen en güzel ışık, hayatımın en değerli anı.",
      "Seninle geçen her saniye, ölümsüz bir aşkın zaman tanımaz kılavuzu.",
      "Varlığın, benim için dünyadaki tüm güzelliklerin toplamı.",
      "Seninle birlikte olmak, tüm dünya zenginliklerinden daha değerli.",
      "Gözlerin, kalbimi en derin yerinden vuran sihirli oklar.",
      "Sen, benim ömrümde bir kez bulunacak nadide bir mücevher.",
      "Sana her dokunuşumda, tüm evrenin sırlarını keşfetmiş gibi hissediyorum.",
      "Senin adın, kalbimin üzerine ölümsüz mürekkeple yazılmış.",
      "Seninle geçirdiğim her gün, hayatımın en güzel sayfaları.",
      "Senin varlığın, ruhumun en büyük ilham kaynağı.",
      "Sen, hayatımın en parlak yıldızı, en derin umudu.",
      "Seninle birlikteyken, zamanın değeri katlanarak artıyor.",
      "Senin gülüşün, dünyaya sığmayan bir mutluluk kaynağı.",
      "Sen, benim kalbimin en kıymetli sırrı, ruhumun ebedi aşkı.",
      "Seninle her konuştuğumda, dünya daha anlamlı, hayat daha güzel.",
      "Senin varlığın, benim için en büyük şükür sebebi.",
      "Sen, hayatıma kattığın her renk için teşekkür edilesi bir sanat eserisin.",
      "Seninle geçen her dakika, kalbimde ölümsüz bir iz bırakıyor.",
      "Gözlerinin içine bakmak, sonsuz bir evrene yolculuk etmek gibi.",
      "Sen, kalbimin en sessiz çığlığı, en gürültülü huzuru.",
      "Senin varlığın, tüm evrene meydan okuyan bir aşk hikayesi.",
      "Seninle birlikte olmak, hayatın tüm zorluklarına karşı koymak gibi güç veriyor.",
      "Sen, benim varoluş sebebim, yaşamak için en büyük nedenim.",
      "Seninle her geçen gün, hayatımın en değerli armağanı oluyor.",
      "Gözlerinde kaybolmak, dünyanın en tatlı serüveni.",
      "Senin varlığın, karanlık gecelerime yıldızlar gibi parlayan umut ışığı.",
      "Seninle birlikteyken hissettiğim huzur, tüm dünyadaki barıştan daha değerli.",
      "Sen, benim en derin düşüncelerimde, en büyük hayallerimdeki eşsiz güzellik.",
      "Senin adın, kalbimdeki en güzel şarkının melodisi.",
      "Senin varlığın, hayatımın en güzel mucizesi, en büyük hediyem.",
      "Seninle geçen zaman, ömrüme ömür katan sihirli bir anahtar.",
      "Sen, hayatımın en değerli bölümü, en unutulmaz hikayesi.",
      "Seninle konuşmak, zamanımı geri alamayacağım bir yatırım gibi.",
      "Bazı insanlar neden suskun, çünkü sen konuşunca kalite düşüyor.",
      "Kendini kitap sanıyorsun ama aslında sadece herkesin bıraktığı bir broşürsün.",
      "Seninle geçirdiğim her an, iyi bir vakit değil, kaybedilmiş zaman.",
      "Seni dinlemek, boş bir kovanın içinde yankılanan ses kadar anlamsız.",
      "Kendini özel hissetme; insanlar sana değil, zamanlarını boşa harcadıklarına üzülüyorlar.",
      "Herkesin bir hikayesi var, seninki ise ne yazık ki kimseyi etkilemiyor.",
      "Bazı insanlar parıldar, sen ise sadece göz yoruyorsun.",
      "Kendine bir iyilik yap, konuşmadan önce bir kez daha düşün.",
      "Gölgende serinleyecek kadar büyük düşünüyorsun ama maalesef sadece güneşi kapatıyorsun.",
      "Seninle aynı fikirde olabilirim ama o zaman ikimiz de yanılmış oluruz.",
      "Biraz daha sessiz olabilir misin? Cehaletin gürültü kirliliği yapıyor.",
      "Eğer akıl bir servet olsaydı, sen muhtemelen dilenirdin.",
      "Kendini bir hazine sandın ama aslında sadece insanların vakit kaybettiği bir bulmacasın.",
      "Senin için en iyi övgü, sessizliğin olacak.",
      "Her şeyi bilmene gerek yok haddini bil yeter.",
      "İnsanlar da fotoğraf gibi; ne kadar büyütürsen, o kadar düşüyor kalitesi.",
      "Bugünlerde hiç kimse arayıp sormuyor. 404 not found gibiyim.",
      "Sesin, beklenmedik bir alarm gibi: Ne zaman çalacağını ve nasıl susturulacağını kimse bilmiyor."
    ];
    
    module.exports = async (message) => {
        if (message.channel.id === conf.chatChannel && !message.author.bot) {
        iltifatSayi++;
        if (iltifatSayi >= 75) {
          iltifatSayi = 0;
          message.reply({ content: iltifatlar.random()});
        };
      };
    }; 

module.exports.conf = {
  name: "messageCreate",
};







