const client = global.btoa;
const { PermissionsBitField, ComponentType, ButtonBuilder, ActionRowBuilder, ButtonStyle, EmbedBuilder, Client, Message, StringSelectMenuBuilder } = require("discord.js");
const ayar = require("../../../../src/configs/ayarName.json");
const { cyronixTik, cyronixRed } = require("../../../../src/configs/emojis.json")
const moment = require("moment")
require("moment-duration-format");

module.exports = {
    conf: {
        name: "ilgiver",
        aliases: ["ilgi","tokat","öp","trip"],
        help: "ilgiver <cyr0nix/ID>",
        category: "kullanıcı", 
    },
    run: async (client, message, args, embed, prefix) => {
        let kanallar = ayar.KomutKullanımKanalİsim;
        if (!message.member.permissions.has(PermissionsBitField.Flags.Administrator) && !kanallar.includes(message.channel.name)) return message.reply({ content: `${kanallar.map(x => `${client.channels.cache.find(chan => chan.name == x)}`)} kanallarında kullanabilirsiniz.`}).then((e) => setTimeout(() => { e.delete(); }, 10000)); 
      
        let member = message.mentions.members.first() || message.guild.members.cache.get(args[0]);
        if (!member) {
            return message.reply({ content: "Bir üye etiketle ve tekrardan dene!" }).then((e) => setTimeout(() => { e.delete(); }, 10000));
        };
        let öpük = ["https://i.pinimg.com/originals/50/6a/c6/506ac6f6a45d6b43cf545451940507bf.gif","https://cdn.discordapp.com/attachments/1213636364503883818/1225316405637812284/elmo-loves-u-elmo.gif?ex=6620afd4&is=660e3ad4&hm=047c52b1120dae8383a93c9afef54fd22801f2504ff2f1b08277295b8e92ca02&","https://cdn.discordapp.com/attachments/1193305796050702346/1201319767601074256/gif-kiss.gif?ex=65c96338&is=65b6ee38&hm=a5f7bc69ec552ad65d096e0bb037218080e87b4ca3e1ae54140a6ee01630abf5&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319768129540096/koi-to-uso-anime.gif?ex=65c96338&is=65b6ee38&hm=39a8209020f4a4dcae755da5590372a45b8b4f44ed2ca9ab7292b07d2f395c1e&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319768557375598/anime-kiss_1.gif?ex=65c96338&is=65b6ee38&hm=c225a8feadeff4a5276ec7d1d3219501f2802ff6716565234f6976914a183dab&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319769043898398/maid-sama.gif?ex=65c96338&is=65b6ee38&hm=1704b474401733acf50318cc63a7d12eacaa57d3b3dae3e7945668822d48f07b&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319769740169358/anime-kiss.gif?ex=65c96338&is=65b6ee38&hm=2e0c7125e589f743cd0d3d37ef86f87e774d0d64a413e8c2f204e42cf5df9010&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319770310578297/kiss-anime-couple.gif?ex=65c96338&is=65b6ee38&hm=7a07bc8a226297be4fd2ede738aa8c077d5f83954cb4b236f99ba90b89974d8f&", "https://cdn.discordapp.com/attachments/1193305796050702346/1201319770767773816/runa-shirakawa-ryuuto-kashima.gif?ex=65c96338&is=65b6ee38&hm=801d000a61766009fc0af8fee2f85474cd746ed2c7178186741e4dfbfdae6b07&"];
    let tokatt = ["https://media.tenor.com/QTfoz_pIxXwAAAAC/recep-recepi%CC%87vedik6.gif",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320274805665822/utku-tokat.gif?ex=65c963b0&is=65b6eeb0&hm=edfebd1082f6fa38f4e2b6373707a67fea151c950a1e9de3c23f39e94cb565eb&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320275342540961/taiga-toradora.gif?ex=65c963b1&is=65b6eeb1&hm=e63fd7398aca289866180e19ca5d12a5256c3cb50ccbb84e1edb8061dfdb703e&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320275854237786/nicole-tompkins.gif?ex=65c963b1&is=65b6eeb1&hm=e248afd5531209aacd49f1a6ac5e868e71e49094322401fe7863b65eb6afdb51&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320276248506438/recep-ivedik-slap-recep-ivedik-tokat.gif?ex=65c963b1&is=65b6eeb1&hm=73ad8b80f4acd68b7289bc12769a19b822efe9b09e68d48ab0110184d83189cf&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320276739244092/danniboi-danniboireface.gif?ex=65c963b1&is=65b6eeb1&hm=976f75d0831ce5078be1908a57e6c2606fe10ab52a15605d9eb84fbb8e9f72d8&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320277083173005/tkthao219-peach.gif?ex=65c963b1&is=65b6eeb1&hm=c7c487165e08e1e0954b688ebbd4593ea7516cffb68babe289adf1d15ff9564e&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320277464858654/90c0a040307beed7.gif?ex=65c963b1&is=65b6eeb1&hm=50b5d28ab5febaf9e7ef9696bc0532420b0338cff4df16ea36e932fa1cfe55bb&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201320277951389706/baby-slap.gif?ex=65c963b1&is=65b6eeb1&hm=d91f28cfdd39ab0cd7d40e5a66ac05f373f443ffca8f0b02397d131367c774b9&"];
    let tripp = ["https://i0.wp.com/img-11.onedio.com/img/719/bound/2r0/55968c08c8b0db794be6b599.gif",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201323816811507814/cute-gif.gif?ex=65c966fd&is=65b6f1fd&hm=c0756ca8ecc956d38153e8645b54cfc3bd69049656d2e5bb66e3f8b546265b63&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201323817319014520/uzme-beni.gif?ex=65c966fd&is=65b6f1fd&hm=1d9800fe248c09741a820e2e9a1d64414bb3ecceb7bd4827ce4193e24078615a&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328873758011422/tom-and-jerry-tom.gif?ex=65c96bb3&is=65b6f6b3&hm=da7ae9affbd6d8a8a7d5f9ad5dbeb65b1c8a06745b125ab3c823edbec12fdc12&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328874139684924/angry-kid.gif?ex=65c96bb3&is=65b6f6b3&hm=d43460fa09f00a155a14c2b5f1a1f8a08c8e44cbf4df7744b9acea6bb6092ad7&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328874521362432/kuswek-kusmek.gif?ex=65c96bb3&is=65b6f6b3&hm=525d9243f935a7d2691111c413e0f7b1863c3dcf9ccfc7c8c6472bb088008ccd&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328874911445012/offended-insulted.gif?ex=65c96bb3&is=65b6f6b3&hm=1e5f4c722001f970b946c8b823e33241674c1703f0970c66ca1490f8e779f6dd&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328875381198980/wendy-darling-peter-pan.gif?ex=65c96bb3&is=65b6f6b3&hm=81ad6ae8e51908e86b1b6589e9e715bbc08fde7b8bd29dee6daaaeb54de0b5ca&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328875733516408/cats-funny-animals.gif?ex=65c96bb3&is=65b6f6b3&hm=aaae198d5f0a109d29ad67327b34faed9ff0807a11670683c0e1f2d7dfaed05b&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201328876127793152/sad-cute.gif?ex=65c96bb3&is=65b6f6b3&hm=24a1f1e16cc1a26bc9cd65a9d6020f0ef47d962727d8eae08164116f3811f8fa&",
    ];
    let ilgii = [
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201325209144262686/heart-shades-on.gif?ex=65c96849&is=65b6f349&hm=311c61006e5a32e8eda9a502be361321f271ad8594538a1985ad92ac6add5d23&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201325209748254790/nuomi-rabbit-unconditional-love.gif?ex=65c96849&is=65b6f349&hm=483cdc6d0acb925bfcea1114ec093983e14dde91f5bdfe5bf8abbf1399430b9f&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201325210272530573/goma-happy.gif?ex=65c96849&is=65b6f349&hm=83ffd1470fa02a439c747110262d86093e500e1ed4fb2d18d7c0a8357a1c41a3&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201325210696159242/kitty-cute.gif?ex=65c96849&is=65b6f349&hm=d7baa1b97a65ee071b080f416fcf7758a9b1fbdb41c8809de79411ebde833cfd&",
        "https://cdn.discordapp.com/attachments/1193305796050702346/1201325211698606100/kitten-kittens.gif?ex=65c9684a&is=65b6f34a&hm=d6c44660298cea8455e629269949309d2457a0db8cc590552d14c32167312269&"];

    const girlNames = [
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Sen benim düşlerimin surete bürünmüş halisin.",
        "Bir sahil kasabasının huzuru birikmiş yüzüne.",
        "Gülüşünde nice ilaçlar var yarama merhem olan.",
        "Gece nasıl sabahı bekliyorsa aydınlanmak için ben de seni öyle bekliyorum.",
        "Işığınla gecemi aydınlatıyorsun.",
        "Yağmurdan sonra açan gök kuşağı gibisin, öyle güzel ve özel!",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan her toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
        "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
        "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
        "Tak jileti dudağına şah damarımdan öp beni!",
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Sen benim düşlerimin surete bürünmüş halisin.",
        "Bir sahil kasabasının huzuru birikmiş yüzüne.",
        "Gülüşünde nice ilaçlar var yarama merhem olan.",
        "Gece nasıl sabahı bekliyorsa aydınlanmak için ben de seni öyle bekliyorum.",
        "Işığınla gecemi aydınlatıyorsun.",
        "Yağmurdan sonra açan gök kuşağı gibisin, öyle güzel ve özel!",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan her toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
        "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
        "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
        "Aklıma sevmek geldiğinde, gözlerimin önüne sen geliyorsun. Günün her saati canım sevmek istiyor ve seni düşünüyor kalbim",
        "Kalbimin tek sahibisin.",
        "Bu gce birşeyler yapsak mı ?  🔥",
        "Yanlıyorum beni söndürmek istermisin 🔥",
        "Tak jileti dudağına şah damarımdan öp beni!",
        "Oha bu çocuk Türk müüüüüüüüüüüü?",
        "dur beynimi çıkarayım, eşit şartlarda konuşalım",
        "gitsen tek kaybım mal kaybı olur hahaha",
        "bunun adı kalp güzelim. Tersten okuduğun gibi plak değil ki sürekli sende takılı kalsın.",
        "kafamı yaşasan kafana sıkarsın",
        "sanırım seni getiren leyleğin bıraktığı izdi, kuş beyinli olman.",
        "senin için savaşırdım ama verimsiz toprakları feth etmeye gerek yok",
        "birbirimizi çift görmem için kaç duble daha içmeliyim?",
        "azrail bile ayağıma geliyor ne bu tripler?",
        "Buralarda yeniyim de kalbinin yolunu tarif eder misin?",
        "Nasıl yani şimdi sen gerçek misin?",
        "Bunca zaman neredeydin ?",
        "seni seviyorum.",
        "Allah seni yaratmış fakat takip etmiyor sanırım, bu tip ne?",
        "sarılalım mı?",
        "benimle evlenir misin?",
        "azıcık beynini kullan diyeceğim fakat seni zor durumda bırakmak istemiyorum.",
        "akıllara zarar bi mükemmelliğin var",
        "attan indiysek leopar falan gelmiştir ben anlamam eşekten",
        "dedikodu yapalım mı?",
        "iyi ki varsın 💕",
        "şu üstteki aptik ne anlatıyor ya?",
        "o kadar haklısın ki... seni öpesim var",
        "öpşuelimi? çabuk!",
        "yavrum hepsi senin mi?",
        "bi alo de gelmezsem gençliğim solsun.",
        "çok şişkosun.",
        "sevgilim var yazma?",
        "zenginsen evlenelim mi?",
        "halk pazarı gibisin canım sana olan tek ilgim ucuzluğundan",
        "o kadar çok meslek türü varken neden şerefsizlik tatlım?",
        "bu güne aynayı öperek başladım",
        "çok bereketli topraklarımız yok mu? her türlü şerefsiz yetişiyor",
        "taş gibisin!",
        "kalitesizliğinin kokusu geldi...",
        "Şey gözlerin çok güzelmiş tanışalım mı ?",
        "Kalbinin yolunu gösterir misin...",
        "Corona olsan bile sana sarılırdım",
        "Oha sen gerçek misin ?",
        "kahveyi sütsüz seni tereddütsüz seviyorum",
        "senin hava attığın yerde benim rüzgarım esiyor",
        "çok güzel bi tablo gördüm tam alacaktım ama aynaymış...",
        "canım haddin hariç her şeyi biliyorsun",
        "havalar alev gibii, tatile serin bi yerlere gitsene mesela morg?",
        "tavla oynayalım ama sen beni tavla",
        "hava sıcak değil aşkından yanıyorum",
        "konum atta belamızı bulalım bebeğim",
        "üşüdüysen sana abayı yakayım mı?",
        "gel biraz otur yanıma ölünce gidersin",
        "sütüm yarım yağlı mutluluğum sana bağlı",
        "eğer ahtapot olsaydım üç kalbimi de sana verirdim",
        "salağa yatarken uyuya falan mı kaldın?",
        "meleksin ama canımı alıyorsun yoksa Azrailim misin?",
        "ben varya fay hattı olsam kesin daha az kırılırdım",
        "iban at hayallerimi yollayayım harcarsın",
        "ankarada deniz sende karakter",
        "sana hayatım diyorum çünkü o kadar kötüsün",
        "görüşelim mi? mahşer yeri uygun mu?",
        "eşekten yarış atı olmaz ama sen genede koş spor yaparsın",
        "Anlatsana biraz neden bu kadar mükemmelsin?",
        "Nasılsın diye sorma bebeğim, sana göreyim kıpss",
        "Kakaolu sütsün seni sevmeyen ölsün",
        "Ya sen hep böyle hoşuma mı gideceksin ?",
        "Çikolatalı keksin bu alemde teksin",
        "8 milyar gülüş varken seninki favorim",
        "dalin gibi kokuyorsun",
        "seni her gün görenlerin şansından istiyorum",
        "en iyisine layıksın yani bana hıh",
        "ateşimin çıkma sebebi corona değil, sensin",
        "yemeğimi yedim şimdi seni yeme vakti",
        "beni biraz takar mısın?",
        "aklın başına gelir ama ben sana gelmem",
        "sen beni birde sevgilinken gör",
        "naber lan karakter kanseri",
        "soğuk davranacaksan üzerime bir şey alayım?",
        "sana beyin alacam",
        "Allah belanı vermiyor artık ben bir şey yapacağım",
        "artık benimsin",
        "o kadar pubg oynadım böyle vurulmadım",
        "canın yandı mı? cenneten düşerken?",
        "seni mumla ararken elektrikler geldi",
        "burnunda sümük var",
        "Suyun içinde klorür senin kalbinde bir ömür...",
        "Çok tatlı olmayı bırak artık... Kalbim başa çıkamıyor !",
        "Kalbini dinle dediklerinde seni dinleyesim geliyor",
        "Polisi arıyorum çünkü bu kadar tatlı olman yasadışı !",
        "Ölüm ani dünya fani bi kere sevsen nolur ki yani ?",
        "Bana yüzünü dönme gece oluyor sanıyorum.",
        "Güneş aya ben sana tutuldum.",
        "Sana gemi alalım dümende bir numarasın.",
        "AÇILIN DÜNYANIN 8.HARİKASI GELDİ !",
        "Ben küçücük bi botum ama sana kocaman sarılırım",
        "Kafam çok güzel çünkü içinde sen varsın.",
        "Alnın güzelmiş yazısı olabilir miyim ?",
        "Gülüşün şimşek içermiyiz birer milkşeyk ?",
        "Gözlerindeki saklı cenneti benden başkası fark etsin istemiyorum.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Huzur kokuyor geçtiğin her yer.",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Biraz Çevrendeki İnsanları Takarmısın ?",
        "İğrenç İnsansın!",
        "Kalbime giden yolu aydınlatıyor gözlerin.  Sadece sen görebilirsin kalbimi. Ve sadece ben hissedebilirim bana karşı olan hislerini.",
        "Onu Bunu Boşver de bize gel 2 bira içelim.",
        "Taş gibi kızsın ama okey taşı… Elden elde gidiyorsun farkında değilsin.",
        "Ateş bacayı sardı ❤️‍🔥",
        "Mucizelerden bahsediyordum.",
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan h er toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
        "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
        "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
        "Aklıma sevmek geldiğinde, gözlerimin önüne sen geliyorsun. Günün her saati canım sevmek istiyor ve seni düşünüyor kalbim."
    ];
    const boyNames = [
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Sen benim düşlerimin surete bürünmüş halisin.",
        "Bir sahil kasabasının huzuru birikmiş yüzüne.",
        "Gülüşünde nice ilaçlar var yarama merhem olan.",
        "Gece nasıl sabahı bekliyorsa aydınlanmak için ben de seni öyle bekliyorum.",
        "Işığınla gecemi aydınlatıyorsun.",
        "Yağmurdan sonra açan gök kuşağı gibisin, öyle güzel ve özel!",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan her toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
        "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
        "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
        "Tak jileti dudağına şah damarımdan öp beni!",
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Sen benim düşlerimin surete bürünmüş halisin.",
        "Bir sahil kasabasının huzuru birikmiş yüzüne.",
        "Gülüşünde nice ilaçlar var yarama merhem olan.",
        "Gece nasıl sabahı bekliyorsa aydınlanmak için ben de seni öyle bekliyorum.",
        "Işığınla gecemi aydınlatıyorsun.",
        "Yağmurdan sonra açan gök kuşağı gibisin, öyle güzel ve özel!",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan her toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.",
        "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.",
        "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.",
        "Aklıma sevmek geldiğinde, gözlerimin önüne sen geliyorsun. Günün her saati canım sevmek istiyor ve seni düşünüyor kalbim",
        "Kalbimin tek sahibisin.",
        "Bu gce birşeyler yapsak mı ?  🔥",
        "Yanlıyorum beni söndürmek istermisin 🔥",
        "Tak jileti dudağına şah damarımdan öp beni!",
        "Oha bu çocuk Türk müüüüüüüüüüüü?",
        "dur beynimi çıkarayım, eşit şartlarda konuşalım",
        "gitsen tek kaybım mal kaybı olur hahaha",
        "bunun adı kalp güzelim. Tersten okuduğun gibi plak değil ki sürekli sende takılı kalsın.",
        "kafamı yaşasan kafana sıkarsın",
        "sanırım seni getiren leyleğin bıraktığı izdi, kuş beyinli olman.",
        "senin için savaşırdım ama verimsiz toprakları feth etmeye gerek yok",
        "birbirimizi çift görmem için kaç duble daha içmeliyim?",
        "azrail bile ayağıma geliyor ne bu tripler?",
        "Buralarda yeniyim de kalbinin yolunu tarif eder misin?",
        "Nasıl yani şimdi sen gerçek misin?",
        "Bunca zaman neredeydin ?",
        "seni seviyorum.",
        "Allah seni yaratmış fakat takip etmiyor sanırım, bu tip ne?",
        "sarılalım mı?",
        "benimle evlenir misin?",
        "azıcık beynini kullan diyeceğim fakat seni zor durumda bırakmak istemiyorum.",
        "akıllara zarar bi mükemmelliğin var",
        "attan indiysek leopar falan gelmiştir ben anlamam eşekten",
        "dedikodu yapalım mı?",
        "iyi ki varsın 💕",
        "şu üstteki aptik ne anlatıyor ya?",
        "o kadar haklısın ki... seni öpesim var",
        "öpşuelimi? çabuk!",
        "yavrum hepsi senin mi?",
        "bi alo de gelmezsem gençliğim solsun.",
        "çok şişkosun.",
        "sevgilim var yazma?",
        "zenginsen evlenelim mi?",
        "halk pazarı gibisin canım sana olan tek ilgim ucuzluğundan",
        "o kadar çok meslek türü varken neden şerefsizlik tatlım?",
        "bu güne aynayı öperek başladım",
        "çok bereketli topraklarımız yok mu? her türlü şerefsiz yetişiyor",
        "taş gibisin!",
        "kalitesizliğinin kokusu geldi...",
        "Şey gözlerin çok güzelmiş tanışalım mı ?",
        "Kalbinin yolunu gösterir misin...",
        "Corona olsan bile sana sarılırdım",
        "Oha sen gerçek misin ?",
        "kahveyi sütsüz seni tereddütsüz seviyorum",
        "senin hava attığın yerde benim rüzgarım esiyor",
        "çok güzel bi tablo gördüm tam alacaktım ama aynaymış...",
        "canım haddin hariç her şeyi biliyorsun",
        "havalar alev gibii, tatile serin bi yerlere gitsene mesela morg?",
        "tavla oynayalım ama sen beni tavla",
        "hava sıcak değil aşkından yanıyorum",
        "konum atta belamızı bulalım bebeğim",
        "üşüdüysen sana abayı yakayım mı?",
        "gel biraz otur yanıma ölünce gidersin",
        "sütüm yarım yağlı mutluluğum sana bağlı",
        "eğer ahtapot olsaydım üç kalbimi de sana verirdim",
        "salağa yatarken uyuya falan mı kaldın?",
        "meleksin ama canımı alıyorsun yoksa Azrailim misin?",
        "ben varya fay hattı olsam kesin daha az kırılırdım",
        "iban at hayallerimi yollayayım harcarsın",
        "ankarada deniz sende karakter",
        "sana hayatım diyorum çünkü o kadar kötüsün",
        "görüşelim mi? mahşer yeri uygun mu?",
        "eşekten yarış atı olmaz ama sen genede koş spor yaparsın",
        "Anlatsana biraz neden bu kadar mükemmelsin?",
        "Nasılsın diye sorma bebeğim, sana göreyim kıpss",
        "Kakaolu sütsün seni sevmeyen ölsün",
        "Ya sen hep böyle hoşuma mı gideceksin ?",
        "Çikolatalı keksin bu alemde teksin",
        "8 milyar gülüş varken seninki favorim",
        "dalin gibi kokuyorsun",
        "seni her gün görenlerin şansından istiyorum",
        "en iyisine layıksın yani bana hıh",
        "ateşimin çıkma sebebi corona değil, sensin",
        "yemeğimi yedim şimdi seni yeme vakti",
        "beni biraz takar mısın?",
        "aklın başına gelir ama ben sana gelmem",
        "sen beni birde sevgilinken gör",
        "naber lan karakter kanseri",
        "soğuk davranacaksan üzerime bir şey alayım?",
        "sana beyin alacam",
        "Allah belanı vermiyor artık ben bir şey yapacağım",
        "artık benimsin",
        "o kadar pubg oynadım böyle vurulmadım",
        "canın yandı mı? cenneten düşerken?",
        "seni mumla ararken elektrikler geldi",
        "burnunda sümük var",
        "Suyun içinde klorür senin kalbinde bir ömür...",
        "Çok tatlı olmayı bırak artık... Kalbim başa çıkamıyor !",
        "Kalbini dinle dediklerinde seni dinleyesim geliyor",
        "Polisi arıyorum çünkü bu kadar tatlı olman yasadışı !",
        "Ölüm ani dünya fani bi kere sevsen nolur ki yani ?",
        "Bana yüzünü dönme gece oluyor sanıyorum.",
        "Güneş aya ben sana tutuldum.",
        "Sana gemi alalım dümende bir numarasın.",
        "AÇILIN DÜNYANIN 8.HARİKASI GELDİ !",
        "Ben küçücük bi botum ama sana kocaman sarılırım",
        "Kafam çok güzel çünkü içinde sen varsın.",
        "Alnın güzelmiş yazısı olabilir miyim ?",
        "Gülüşün şimşek içermiyiz birer milkşeyk ?",
        "Gözlerindeki saklı cenneti benden başkası fark etsin istemiyorum.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Huzur kokuyor geçtiğin her yer.",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Biraz Çevrendeki İnsanları Takarmısın ?",
        "İğrenç İnsansın!",
        "Kalbime giden yolu aydınlatıyor gözlerin.  Sadece sen görebilirsin kalbimi. Ve sadece ben hissedebilirim bana karşı olan hislerini.",
        "Onu Bunu Boşver de bize gel 2 bira içelim.",
        "Taş gibi kızsın ama okey taşı… Elden elde gidiyorsun farkında değilsin.",
        "Ateş bacayı sardı ❤️‍🔥",
        "Mucizelerden bahsediyordum.",
        "Mucizelerden bahsediyordum. Tam o sırada gözlerin geldi aklıma.",
        "Benim için mutluluğun tanımı, seninle birlikteyken geçirdiğim vakittir.",
        "Mavi gözlerin, gökyüzü oldu dünyamın.",
        "Seni gören kelebekler, narinliğin karşısında mest olur.",
        "Parlayan gözlerin ile karanlık gecelerime ay gibi doğuyorsun.",
        "Sabah olmuş. Sen mi uyandın yoksa gönlüme güneş mi doğdu.",
        "Huzur kokuyor geçtiğin her yer.",
        "En güzel manzaramsın benim, seyretmeye doyamadığım.",
        "Öyle bir duru güzelliğin var ki, seni gören şairler bile adına günlerce şiir yazardı.",
        "Gözlerinin hareketi bile yeter  benim aklımı başımdan almaya.",
        "Seni kelimeler ile anlatmak çok zor. Muhteşem desem yine eksik kalıyor anlamın.",
        "Güller bile kıskanır seni gördükleri zaman kendi güzelliklerini.",
        "Hiç yazılmamış bir şiirsin sen, daha önce eşi benzeri olmayan.",
        "Bu kadar muhteşem olamaz bir insan. Bu kadar kusursuz bu kadar mükemmel.. Kirpiklerinin dizilişi bile sırayla senin.",
        "Adım şaire çıktı civarda. Kimse senin şiir olduğunun farkında değil henüz.",
        "Senin güzelliğini anlatmaya dünyalar değil, lisanlar bile yetmez.",
        "Etkili gülüş kavramını ben senden öğrendim.",
        "Seni yanlışlıkla cennetten düşürmüşler. Dünyada yaşayan bir meleksin sen.",
        "Seni anlatmaya kelimeler bulamıyorum. Nasıl anlatacağımı bilemediğim için seni kimselere anlatamıyorum.",
        "Gözlerinin gördüğü her yer benimdir. Bakışına şahit olan h er toprak benim de vatanımdır.",
        "Gözlerinle baharı getirdin garip gönlüme.",
        "Bir gülüşün ile çiçek açıyor bahçemdeki her bir çiçek.",
        "Yuva kokuyor kucağın. Sarılınca seninle yuva kurası geliyor insanın.",
        "Seni de bu dünyada görünce yaşama sebebimi anladım. Meğer senmişsin beni dünyada yaşamaya zorlayan.",
        "Sen bu  dünyadaki bütün şarkıların tek sahibisin. Sana yazılıyor bütün şarkılar ve şiirler. Adın geçiyor bütün namelerde.",
        "Sen benim yanımda olduğun sürece benim nerde olduğum hiç önemli değil .Kokunu aldığım her yer cennet bana.",
        "Seni yüreğimde taşıyorum ben, sırtımda taşımak ne kelime. Ömrüm boyunca çekmeye hazırım her anlamda senin yükünü.",
        "Hayatıma gelerek hayatımdaki bütün önemli şeylerin önemsiz olmasını sağladın. Artık sensin tek önem verdiğim şu hayatta.",
        "Sen benim bu hayattaki en büyük duamsın.  Gözlerin adeta bir ay parçası. Işık oluyorsun karanlık gecelerime.",
        "Aynı zaman diliminde yaşamak benim için büyük ödüldür.",
        "Seninle aşkı yaşamak çok güzel bir şey ama sensiz kalma korkusunu düşünmek korkutuyor beni.",
        "Seni severek meslek sahibi oldum ben. Seni sevmeye başladıkça şair oldum.",
        "Gülüşün güzelliğine anlam katıyor. Gamzelerin ise bambaşka diyarların kapılarını açıyor.",
        "Senin gülüşünü gördüğüm günden beri ağlamalarımı unuttum.", "Kimse konuşmasın yalnız sen konuş bana. Yalnız sen bak gözlerimin içine. Kimse olmasın yalnızca sen ol benim hayatımda.",
        "Ben seninle birlikte yaşayabilmek için ikinci kere geldim hayata.", "Senin attığın adımlarda seni korumak için geçtiğin yol olmak isterdim. Seni emniyete alan ve sonsuz bir yolculuğa çıkaran bir yol.", "Aklıma sevmek geldiğinde, gözlerimin önüne sen geliyorsun. Günün her saati canım sevmek istiyor ve seni düşünüyor kalbim."
    ];
    const gender = Math.random() < 0.5 ? 'Kız' : 'Erkek'; // Rastgele bir cinsiyet seçimi

    let randomName;

    if (gender === 'Kız') {
        randomName = girlNames[Math.floor(Math.random() * girlNames.length)];
        // Kız çocuğu isteği mesajı
    } else {
        randomName = boyNames[Math.floor(Math.random() * boyNames.length)];
        // Erkek çocuğu isteği mesajı
    }
    const row = new ActionRowBuilder()

        .addComponents(
            new StringSelectMenuBuilder()
                .setPlaceholder('İltifat Et/İlgi Ver/Trip At /Öp/ Tokat')
                .setCustomId('kurulumselect')
                .addOptions([
                    {
                        label: "İltifat Et",
                        value: "iltifat",
                        description: "İltifat Etdersin",
                        emoji: "1094619366143823962"

                    },
                    {
                        label: "İlgi Ver!",
                        value: "ilgi",
                        description: "İlgi sevgi verir",
                        emoji: "935966185319723048"

                    },
                    {
                        label: "Trip!",
                        value: "süründür",
                        description: "Trip atarak süründürür",
                        emoji: "1191449207320621096"

                    },
                    {
                        label: "Öp!",
                        value: "öp",
                        description: "Öpücük verir",
                        emoji: "935965311486787654"

                    },
                    {
                        label: "Tokat!",
                        value: "tokat",
                        description: "Tokat Atar.",
                        emoji: "992864405748461578"

                    },
                    {
                        label: "Kapat",
                        description: "Menüyü kapatır.",
                        value: "closeMenu",
                        emoji: "998715544683434115"
                    }
                ])
        );
    const ramal = new EmbedBuilder()
        .setDescription(`Birileri bişeyler mi yapmak istiyormuşş ne
Heyy ${member} ${message.author} sana karşı bir eylem uygulamak iştiyor.

Ayrıca aşağıdaki menüden istediğiniz diğer istekleri de uygulayabilirsiniz.`)

        .setAuthor({ name: message.guild.name, iconURL: message.guild.iconURL({ dynamic: true }) })
        .setThumbnail(message.guild.iconURL({ dynamic: true, size: 2048 }))
    let msg = await message.channel.send({ content: `${member}`,embeds: [ramal], components: [row],   })
    message.react(cyronixTik);
    const filter = i => i.user.id == message.author.id
    const collector = msg.createMessageComponentCollector({ filter, componentType: ComponentType.StringSelect, max: 1, time: 50000 });

    collector.on("collect", async (interaction) => {
        if (interaction.values[0] == "iltifat") {
            const iltifat = new EmbedBuilder()
                .setDescription(`${member} **${randomName}**`)

            interaction.update({ embeds: [iltifat], components: [],ephemaral: true })
        }
        if (interaction.values[0] == "ilgi") {

            const ilgi = new EmbedBuilder()
                .setDescription(`${member} Birileri Senden Hoşlanıyorrr.`)
                .setImage(`${ilgii[Math.floor(Math.random() * 6)]}`)

            interaction.update({ embeds: [ilgi], components: [],ephemeral: true })
        }
        if (interaction.values[0] == "süründür") {

            const süründür = new EmbedBuilder()
                .setDescription(`${member} Uzak Dur Benden.`)
                .setImage(`${tripp[Math.floor(Math.random() * 10)]}`)

            interaction.update({ embeds: [süründür], components: [],ephemeral: true })
        }
        if (interaction.values[0] == "öp") {
            const öp = new EmbedBuilder()
                .setDescription(`${member} Öptüm bay,Yaptım say.`)
                .setImage(`${öpük[Math.floor(Math.random() * 8)]}`)
            interaction.update({ embeds: [öp], components: [],ephemeral: true })
        }
        if (interaction.values[0] == "tokat") {
            const öp = new EmbedBuilder()
                .setDescription(`${member} ŞAK ŞAK ŞAK.`)
                .setImage(`${tokatt[Math.floor(Math.random() * 9)]}`)

            interaction.update({ embeds: [öp], components: [],ephemeral: true })
        }
        if (interaction.values[0] == "closeMenu") {
            interaction.message.delete()
        }
        collector.on("collect", async (interaction) => {
            if (interaction.customId === "msj") {
                interaction.message.delete();
                message.delete();
            }
        })
    }
    )
    }
}